# Generated by Django 4.0.5 on 2022-06-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmsap2', '0006_rename_segment1_id_ratio_segment1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='ratio_searched',
            field=models.BooleanField(default=False),
        ),
    ]
