# Generated by Django 4.0.5 on 2022-06-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmsap2', '0011_skipgroup_skipgroupcategory_alter_ratio_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervals',
            name='part_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
