# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170903_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='frag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='composer',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='main.Composer'),
        ),
    ]
