# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170903_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='composer',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
