# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170903_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='composer',
            field=models.PositiveIntegerField(db_column='composer_id', default=12),
        ),
    ]
