# Generated by Django 4.0.4 on 2022-06-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_id', models.IntegerField()),
                ('chord_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_canonical', models.BooleanField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('sort_year', models.IntegerField(blank=True, null=True)),
                ('earliest_year', models.IntegerField(blank=True, null=True)),
                ('latest_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('piece_name', models.CharField(blank=True, max_length=255, null=True)),
                ('frag', models.BooleanField(blank=True, null=True)),
                ('composer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='emmsap2.composer')),
            ],
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('language', models.CharField(blank=True, max_length=4, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('text_reg', models.TextField(blank=True, null=True)),
                ('text_no_space', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TinyNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(blank=True, max_length=255, null=True)),
                ('part_id', models.IntegerField(blank=True, null=True)),
                ('ts_ratio', models.CharField(blank=True, max_length=10, null=True)),
                ('tn', models.TextField(blank=True, null=True)),
                ('tn_strip', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('fn', 'part_id')},
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.IntegerField(blank=True, null=True)),
                ('segment_id', models.IntegerField(blank=True, null=True)),
                ('measure_start', models.IntegerField(blank=True, null=True)),
                ('measure_end', models.IntegerField(blank=True, null=True)),
                ('encoding_type', models.CharField(blank=True, max_length=20, null=True)),
                ('segment_data', models.CharField(blank=True, max_length=40, null=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emmsap2.piece')),
            ],
        ),
        migrations.CreateModel(
            name='RatiosDiaRhy2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.SmallIntegerField(db_index=True)),
                ('segment1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment1s', to='emmsap2.segment')),
                ('segment2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment2s', to='emmsap2.segment')),
            ],
        ),
        migrations.CreateModel(
            name='Intervals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(blank=True, max_length=255, null=True)),
                ('part_id', models.IntegerField(blank=True, db_column='partId', null=True)),
                ('intervals', models.TextField(blank=True, null=True)),
                ('intervals_no_unisons', models.TextField(blank=True, null=True)),
                ('intervals_with_rests', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('fn', 'part_id')},
            },
        ),
        migrations.AddField(
            model_name='composer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emmsap2.country'),
        ),
    ]
