# Generated by Django 4.0.4 on 2022-06-07 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emmsap2', '0002_alter_piece_composer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tinynotation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='segment',
            name='segment_id',
        ),
        migrations.RemoveField(
            model_name='texts',
            name='fn',
        ),
        migrations.AddField(
            model_name='texts',
            name='piece',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emmsap2.piece'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tinynotation',
            name='piece',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emmsap2.piece'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tinynotation',
            unique_together={('piece', 'part_id')},
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['piece'], name='emmsap2_seg_piece_i_ec9f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['encoding_type'], name='emmsap2_seg_encodin_7ba86a_idx'),
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['part_id'], name='emmsap2_seg_part_id_a39649_idx'),
        ),
        migrations.RemoveField(
            model_name='tinynotation',
            name='fn',
        ),
    ]
