# Generated by Django 4.0.4 on 2022-06-07 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emmsap2', '0003_alter_tinynotation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.SmallIntegerField(db_index=True)),
                ('encoding_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='segment',
            name='encoding_type',
            field=models.CharField(default='DiaRhy2', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RatiosDiaRhy2',
        ),
        migrations.AddField(
            model_name='ratios',
            name='segment1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment1s', to='emmsap2.segment'),
        ),
        migrations.AddField(
            model_name='ratios',
            name='segment2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment2s', to='emmsap2.segment'),
        ),
        migrations.AddIndex(
            model_name='ratios',
            index=models.Index(fields=['encoding_type'], name='emmsap2_rat_encodin_24ad18_idx'),
        ),
    ]
