# Generated by Django 4.0.5 on 2022-06-08 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emmsap2', '0005_rename_ratios_ratio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratio',
            old_name='segment1_id',
            new_name='segment1',
        ),
        migrations.RenameField(
            model_name='ratio',
            old_name='segment2_id',
            new_name='segment2',
        ),
    ]
