# Generated by Django 4.0.5 on 2022-06-08 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emmsap2', '0007_segment_ratio_searched'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=4, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('text_reg', models.TextField(blank=True, null=True)),
                ('text_no_space', models.TextField(blank=True, null=True)),
                ('piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emmsap2.piece')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='intervals',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chords',
            name='piece_id',
        ),
        migrations.AddField(
            model_name='chords',
            name='piece',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='emmsap2.piece'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervals',
            name='piece',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='emmsap2.piece'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='intervals',
            unique_together={('piece', 'part_id')},
        ),
        migrations.DeleteModel(
            name='Texts',
        ),
        migrations.RemoveField(
            model_name='intervals',
            name='fn',
        ),
    ]
