# Generated by Django 4.0.5 on 2022-06-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmsap2', '0008_text_alter_intervals_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervals',
            name='intervals_one_char',
            field=models.TextField(blank=True, null=True),
        ),
    ]
