# Generated by Django 4.0.5 on 2022-06-10 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emmsap2', '0010_alter_intervals_piece'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkipGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SkipGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ratio',
            name='ratio',
            field=models.SmallIntegerField(),
        ),
        migrations.CreateModel(
            name='SkipPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emmsap2.piece')),
                ('skip_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emmsap2.skipgroup')),
            ],
        ),
        migrations.AddField(
            model_name='skipgroup',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emmsap2.skipgroupcategory'),
        ),
    ]
