# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20150827_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.RemoveField(
            model_name='piece',
            name='composer_id',
        ),
        migrations.AddField(
            model_name='piece',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Composer'),
        ),
    ]
